### ISSUE TITLE
Unable to retrieve data from Cassandra DB

### ISSUE THREAD

**Issue by jcouelier** [noralife/node-red-contrib-cassandra#5]
I have tried to do a CQL query on my Cassandra DB and as soon as I am using timestamp filter i obtain error due to a problem of buffer length.
I have opened a ticket on the forum and following dceejay advice i am creating a new issue for my problem.

Description below:

Below is my traces:

3 Apr 11:40:03 - [info] [function:convert UNIXtime to startDate ] 1585309203485

3 Apr 11:40:03 - [info] [function:convert UNIXtime to startDate ] Fri Mar 27 2020 11:40:03 GMT+0000 (UTC)

3 Apr 11:40:03 - [info] [function:convert UNIXtime to startDate ] 2020

3 Apr 11:40:03 - [info] [function:data extraction] select tagdataid, timestamp, assetidentifier, batterylevel, temperature, energy, humidity, power, pressure, profilename, tagidentifier from lbs.tagdatatable where assetidentifier='tousSensors' and timestamp>='2020-3-27 0:0:0.0' and timestamp<='2020-4-1 23:59:59.999' allow filtering;

3 Apr 11:40:03 - [info] [cassandra:b1d642fe.1031c] Executing CQL query:
3 Apr 11:40:03 - [info] [function:convert UNIXtime to endDate ] 1585914003485
3 Apr 11:40:03 - [info] [function:convert UNIXtime to endDate ] Fri Apr 03 2020 11:40:03 GMT+0000 (UTC)
3 Apr 11:40:03 - [info] [function:convert UNIXtime to endDate ] 2020
3 Apr 11:40:03 - [info] [function:data extraction] select tagdataid, timestamp, assetidentifier, batterylevel, temperature, energy, humidity, power, pressure, profilename, tagidentifier from lbs.tagdatatable where assetidentifier='tousSensors' and timestamp>='2020-3-27 0:0:0.0' and timestamp<='2020-4-3 23:59:59.999' allow filtering;
3 Apr 11:40:03 - [info] [cassandra:b1d642fe.1031c] Executing CQL query:
3 Apr 11:40:05 - [red] Uncaught Exception:
3 Apr 11:40:05 - RangeError: Trying to access beyond buffer length
at FrameReader.checkOffset (/usr/src/node-red/node_modules/cassandra-driver/lib/readers.js:119:15)
at FrameReader.readString (/usr/src/node-red/node_modules/cassandra-driver/lib/readers.js:107:8)
at FrameReader.readError (/usr/src/node-red/node_modules/cassandra-driver/lib/readers.js:315:22)
at Parser.parseBody (/usr/src/node-red/node_modules/cassandra-driver/lib/streams.js:180:66)
at Parser._transform (/usr/src/node-red/node_modules/cassandra-driver/lib/streams.js:135:10)
at Parser.Transform._read (_stream_transform.js:186:10)
at Parser.Transform._write (_stream_transform.js:174:12)
at doWrite (_stream_writable.js:396:12)
at writeOrBuffer (_stream_writable.js:382:5)
at Parser.Writable.write (_stream_writable.js:290:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.0 start: node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-red-docker@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above

The error seems to be a problem of javascript buffer management when receiving message (but not sure at all).

**Comment by nicolasbertaud** [comment]
In the traces i think  the timestamps are not well formatted 
timestamp>='2020-3-27 0:0:0.0' and timestamp<='2020-4-3 23:59:59.999'

**Comment by nicolasbertaud** [comment]
it should be 
timestamp>='2020-03-27 00:00:00.000' and timestamp<='2020-04-03 23:59:59.999'
refer to  https://docs.datastax.com/en/archived/cql/3.3/cql/cql_reference/timestamp_type_r.html
